apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wsh2025
  namespace: wsh2025
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: wsh2025.kentaro1043.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: wsh2025-service
                port:
                  number: 80
            path: /
